site_name: Utilz
site_description: "Utility library for faster, easier, and more reliable data analysis"
site_url: "https://eshinjolly.com/utilz"
repo_url: "https://github.com/ejolly/utilz"
repo_name: "ejolly/utilz"
theme:
  name: material
extra_css:
  - custom.css
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
nav:
  - Home: index.md
  - Saving and Loading: api/io.md
  - Data analysis "verbs": api/verbs.md
  - Guards and Decorators: api/guards.md
  - Plotting Helpers: api/plot.md
  - Operations: api/ops.md
  - Boilerplate: api/boilerplate.md
  - Terminal Plots (experimental): api/termplot.md
  - Pipe Operator (experimental): api/pipe.md
  - Usage Examples:
      - Declarative Data Analysis: api/fp_data_analysis.ipynb
plugins:
  - mkdocs-jupyter
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            filters:
              - "!^_"
              - "!^MAX"
          rendering:
            show_source: true
            show_if_no_docstring: true
            heading_level: 4
      watch:
        - utilz
