site_name: Utilz
site_description: "Utility library for faster, easier, and more reliable data analysis"
site_url: "https://eshinjolly.com/utilz"
repo_url: "https://github.com/ejolly/utilz"
repo_name: "ejolly/utilz"
theme:
  name: material
extra_css:
  - custom.css
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
nav:
  - Home: index.md
  - Quick Overview: intro.ipynb
  - Working with Pipes: pipes.md
  - API:
      - Core: api/core.md
plugins:
  - mkdocs-jupyter:
      ignore: ["dev/*"]
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            show_source: true
            show_if_no_docstring: false
            heading_level: 4
      watch:
        - utilz
