site_name: Utilz
site_description: "Utility library for faster, easier, and more reliable data analysis"
site_url: "https://eshinjolly.com/utilz"
repo_url: "https://github.com/ejolly/utilz"
repo_name: "ejolly/utilz"
theme:
  name: material
extra_css:
  - custom.css
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
nav:
  - Home: index.md
  - API Reference:
      - Saving and Loading: api/io.md
      - Guards and Decorators: api/guards.md
      - Operations: api/ops.md
      - Pipe Operator: api/pipe.md
      - Terminal Plots: api/termplot.md
      - Plotting Helpers: api/plot.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            filters:
              - "!^_"
              - "!^MAX"
          rendering:
            show_source: true
            show_if_no_docstring: true
            heading_level: 4
      watch:
        - utilz
