name: Utilz

on:
  push:
    branches:
      - master
      - main
      - pyproject
  workflow_dispatch:

jobs:
  # Job (1): Run testing in parallel against multiples OSs and Python versions
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # OSs to test
        os: [ubuntu-latest]
        # Python versions to test
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

        # See also: https://github.com/marketplace/actions/install-poetry-action when
        # testing on more OSs
      - name: Setup Environment
        run: |
          curl -sSL https://install.python-poetry.org | python
          poetry install

      # 4. Actually run the tests with coverage
      - name: Run Tests
        run: |
          poetry run python --version
          poetry run coverage run --source=utilz -m pytest

      - name: Build docs
        run: poetry run mkdocs build

      - name: Build package
        run: poetry build

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
