name: Utilz

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]
        exclude:
          - os: [mac-os-latest, windows-latest]
            python-version: 3.9
    steps:
      - name: Download and setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          conda activate test
          conda env list
          conda install -y pip numpy pandas scipy matplotlib seaborn scikit-learn
          conda install -y -c conda-forge pytest coveralls
          pip install . -r requirements.txt

      - name: Run Tests
        run: |
          conda activate test
          conda env list
          coverage run --source=utilz -m pytest

      - name: Upload Coverage
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: $${{ matrix}}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Build and deploy package
    needs: coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        shell: bash
        run: |
          echo "hello world. I havent been configured for deployment yet!"
